### ISSUE TITLE
Create Course View

### ISSUE THREAD

**Issue by abrokinla** [EduSchola/EduSchola#7]
The Create Course view on the backend is responsible for handling the API endpoints and database operations related to the Course model in the EduSchola project. It provides the necessary functionality to create, retrieve, update, and delete course records through API requests.

Tasks:

Implement Create Course API:

Design and implement an API endpoint that accepts HTTP POST requests to create a new course.
Handle the request payload, validate the input data, and create a new Course object.
Save the new course record to the database.

Implement Retrieve Course API:

Design and implement an API endpoint that accepts HTTP GET requests to retrieve course data.
Fetch and return a list of existing courses from the database.
Include any necessary filtering, sorting, or pagination options based on project requirements.

Implement Update Course API:

Design and implement an API endpoint that accepts HTTP  PATCH requests to update a course.
Handle the request payload, validate the input data, and update the corresponding course record in the database.
Implement Delete Course API:

Design and implement an API endpoint that accepts HTTP DELETE requests to delete a course.
Retrieve the course record based on the provided ID and delete it from the database.

Write Backend Tests for Course APIs:

Write test cases to cover the functionality of the Create, Retrieve, Update, and Delete APIs for the Course model.
Test various scenarios, including success cases, error handling, and edge cases.
Ensure proper test coverage for different API endpoints and scenarios.

Remember to follow your project's coding style, guidelines, and naming conventions throughout the implementation.

**Comment by whoissegun** [comment]
issue has been resolved
