### ISSUE TITLE
Create Assignment Views

### ISSUE THREAD

**Issue by abrokinla** [EduSchola/EduSchola#8]
The Create Assignment view on the backend is responsible for handling the API endpoints and database operations related to the Assignment model in the EduSchola project. It provides the necessary functionality to create, retrieve, update, and delete assignment records through API requests.

Tasks:

Implement Create Assignment API:

Design and implement an API endpoint that accepts HTTP POST requests to create a new assignment.
Handle the request payload, validate the input data, and create a new Assignment object.
Save the new assignment record to the database.

Implement Retrieve Assignment API:

Design and implement an API endpoint that accepts HTTP GET requests to retrieve assignment data.
Fetch and return a list of existing assignments from the database.
Include any necessary filtering, sorting, or pagination options based on project requirements.

Implement Update Assignment API:

Design and implement an API endpoint that accepts HTTP PUT or PATCH requests to update an assignment.
Handle the request payload, validate the input data, and update the corresponding assignment record in the database.

Implement Delete Assignment API:

Design and implement an API endpoint that accepts HTTP DELETE requests to delete an assignment.
Retrieve the assignment record based on the provided ID and delete it from the database.

Write Backend Tests for Assignment APIs:

Write test cases to cover the functionality of the Create, Retrieve, Update, and Delete APIs for the Assignment model.
Test various scenarios, including success cases, error handling, and edge cases.
Ensure proper test coverage for different API endpoints and scenarios.

Remember to follow your project's coding style, guidelines, and naming conventions throughout the implementation.

**Comment by whoissegun** [comment]
issue has been resolved
