### ISSUE TITLE
Create School Views

### ISSUE THREAD

**Issue by abrokinla** [EduSchola/EduSchola#9]
The Create School view on the backend/API is responsible for handling the API endpoints and database operations related to creating new schools in the EduSchola project. This view provides the necessary functionality to create schools through API requests.

Tasks:

Implement Create School API:

Design and implement an API endpoint that accepts HTTP POST requests to create a new school.
Handle the request payload, validate the input data, and create a new School object.
Save the new school to the database.

Implement Validation and Data Sanitization:

Validate the input data for the school creation API.
Ensure required fields are present and have valid data.
Sanitize and transform the data as necessary to prevent any security vulnerabilities or data inconsistencies.

Write Backend Tests for Create School API:

Write test cases to cover the functionality of the Create School API.
Test various scenarios, including success cases, error handling, and edge cases.
Ensure proper test coverage for the API endpoint.

Error Handling and Responses:

Implement appropriate error handling for the Create School API.
Return meaningful error responses with proper status codes and error messages when necessary.

Remember to follow your project's coding style, guidelines, and naming conventions throughout the implementation.

**Comment by whoissegun** [comment]
issues has been resolved
